### ISSUE TITLE
Difference when providing hyperlink reference

### ISSUE THREAD

**Issue by Basreena** [project-sunbird/project-sunbird.github.io#111]
When providing hyperlink reference for image, the path takes the folder name and image name. However when providing hyperlink for pages, the link starts with the pages to folder to file name. Please rectify. For consitency, the path taken should be same. Either both the path for image and pages takes only folder name and image name or the link starts with pages to file name. In either case, it should be same for both.

**Comment by lakhanmandloi** [comment]
This is fixed and will be updated soon with Multi-version Documentation.
