### ISSUE TITLE
Sequential number rendered incorrectly

### ISSUE THREAD

**Issue by Basreena** [project-sunbird/project-sunbird.github.io#115]
When providing sequential instructions in github, the numbering appears sequentailly correct but on the website it is rendered incorrectly. While on github it si 1,2,3, it gets rendered as 1,1,1 on the website.

**Comment by coolbung** [comment]
Please share reference links

**Comment by lakhanmandloi** [comment]
@Basreena @nawabahmadreshi @Sunitashelar @deepshikha2k5 

Indention was required.
