### ISSUE TITLE
Website doesnot render correctly on mobile

### ISSUE THREAD

**Issue by Basreena** [project-sunbird/project-sunbird.github.io#116]
When browsing the website on mobile, the following problems were noted:

- Tables are rendered completely. The whole table is not visible.
- Cannot scroll vertically to view the entire table
- Cannot expand the screen
- The burger menu is clickable only once. It does not respong to subsequent clicks

**Comment by lakhanmandloi** [comment]
@Basreena @Sunitashelar @nawabahmadreshi @deepshikha2k5 

Hi,

All issues mentioned in this thread are resolved now. 

Thanks!
