### ISSUE TITLE
Documentation issue- Install Sunbird on Laptop

### ISSUE THREAD

**Issue by sunil-optit** [project-sunbird/project-sunbird.github.io#125]
In the documentation under Install Sunbird on laptop the "Edit Application Config"
For the parameter module.exports it is not understandable as to what should be modified since there are continuation punctuation consisting of dots.

In the original file the entire parameter- module.exports is not present

**Comment by nawabahmadreshi** [comment]
https://github.com/project-sunbird/project-sunbird.github.io/pull/146

done and under review

**Comment by nawabahmadreshi** [comment]
https://github.com/project-sunbird/project-sunbird.github.io/pull/146
