### ISSUE TITLE
Add a page for Telemetry spec

### ISSUE THREAD

**Issue by kochhar** [project-sunbird/project-sunbird.github.io#126]
New page is required for telemetry spec. 

Hierarchy is:
Documentation > Developer Documentation > API Reference > Telemetry Spec

Please add to the left navigation also.

**Comment by nawabahmadreshi** [comment]
@kochhar 
Edit the contents here , 
http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/review/developer-docs/telemetry_spec/

I have already added the link it to sidebar but its commented till the content is finalised.

**Comment by nawabahmadreshi** [comment]
any updates @kochhar

**Comment by kochhar** [comment]
@Sunitashelar will you be updating the telemetry spec or should I update it?

**Comment by kochhar** [comment]
This item is a duplicate of: https://github.com/project-sunbird/project-sunbird.github.io/issues/163

**Comment by Sunitashelar** [comment]
closed
