### ISSUE TITLE
Need documentation on how to submit a bug report

### ISSUE THREAD

**Issue by kochhar** [project-sunbird/project-sunbird.github.io#127]
sunbird.org website is missing a section on how to submit a bug report.

**Comment by kochhar** [comment]
Could I please get an updated eta @nawabahmadreshi @Sunitashelar @shelarsunita

**Comment by nawabahmadreshi** [comment]
@kochhar 
Review please:
http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/review/contributions/filing_a_bug/

**Comment by kochhar** [comment]
Overview, introduction, guidelines & prerequisites sections can be removed
entirely.
The issue tracker location is wrong.
The bullet points on filing a new bug are the main part of the document.
Please rewrite that. Here's a reference:
https://musescore.org/en/developers-handbook/how-write-good-bug-report-step-step-instructions

Bug lifecycle and bug review can be moved.
Issue labels and Other bug related terminology can be moved.

**Comment by nawabahmadreshi** [comment]
Kindly review
http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/review/contributions/filing_a_bug/
@Sunitashelar @kochhar

**Comment by nawabahmadreshi** [comment]
done 12/1 and sent for review

**Comment by nawabahmadreshi** [comment]
http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/review/contributions/filing_a_bug/
@kochhar 
kindly review so that I  push it to production

**Comment by kochhar** [comment]
I have updated the file. Please take a look and merge if ok.

**Comment by nawabahmadreshi** [comment]
published
