### ISSUE TITLE
Installation options section is missing header formatting

### ISSUE THREAD

**Issue by kochhar** [project-sunbird/project-sunbird.github.io#130]
Heading levels are missing for the installation options

cc: @Sunitashelar

**Comment by Sunitashelar** [comment]
resolved.

**Comment by kochhar** [comment]
Please share a preview @Sunitashelar

**Comment by Sunitashelar** [comment]
@kochhar  all commits can be viewed here, until we push to production:
http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/review/developer-docs/installation/

**Comment by Sunitashelar** [comment]
@kochhar the above is only for the installation overview page. The site is:
http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com
