### ISSUE TITLE
Install on laptop page has formatting errors under "run the application"

### ISSUE THREAD

**Issue by kochhar** [project-sunbird/project-sunbird.github.io#131]
Section on Run the following commands (at the bottom of the page) should be in code formatting.

cc: @Sunitashelar

**Comment by nawabahmadreshi** [comment]
@kochhar , fixed it .You can check it here .
http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/review/developer-docs/installation/installing_sunbirdon_laptop/
