### ISSUE TITLE
Deploy sunbird services page needs outline

### ISSUE THREAD

**Issue by kochhar** [project-sunbird/project-sunbird.github.io#133]
Deploy sunbird services page is missing an outline
http://www.sunbird.org/developer-docs/installation/deploy_sb_services/

cc:@sunitashelar

**Comment by deepshikha2k5** [comment]
Issue resolved

**Comment by kochhar** [comment]
Thanks, could you link the new build?

**Comment by shelarsunita** [comment]
hi, there is a new build process to push from qa to production. lakhan needs to update us with the same. @lakhanmandloi , could you please push all updates to production now and make us conversant with the new process at the earliest?

**Comment by nawabahmadreshi** [comment]
@deepshikha2k5  is this done ?

**Comment by deepshikha2k5** [comment]
Yeh Nawab I have set the page outline.

**Comment by coolbung** [comment]
I've updated the services installation page. It's in this MR
https://github.com/project-sunbird/project-sunbird.github.io/pull/145

**Comment by nawabahmadreshi** [comment]
@coolbung 
Will check and revert back if needed.

**Comment by Sunitashelar** [comment]
closed
