### ISSUE TITLE
Keycloak realm configuration page outline is incorrect

### ISSUE THREAD

**Issue by kochhar** [project-sunbird/project-sunbird.github.io#134]
http://www.sunbird.org/developer-docs/installation/keycloak_realm_configuration/
Keycloak realm config has all items as sub-items of getting started. Sub-items should be siblings of getting started.

cc:@sunitashelar

**Comment by nawabahmadreshi** [comment]
@kochhar 
preview the changes here 
http://www.sunbird.org/developer-docs/installation/keycloak_realm_configuration/
