### ISSUE TITLE
Customise assets page code formatting is incorrect

### ISSUE THREAD

**Issue by kochhar** [project-sunbird/project-sunbird.github.io#135]
Code formatting on customising assets page is incorrect. Code should be formatted in blocks
http://www.sunbird.org/developer-docs/installation/cust_sunbird/

cc:@Sunitashelar

**Comment by nawabahmadreshi** [comment]
http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/review/developer-docs/installation/cust_sunbird/

**Comment by kochhar** [comment]
There is no change in the linked page. The formatting has not been fixed.

**Comment by nawabahmadreshi** [comment]
The website page is updated though, the internally linked page redirects to another repository.

**Comment by kochhar** [comment]
Code blocks are not formatted correctly in this page. Re-opening issue. @nawabahmadreshi we can discuss if it's unclear.

**Comment by nawabahmadreshi** [comment]
http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/review/developer-docs/installation/cust_sunbird/

If still this is not as per the requirement, yes we can discuss this ,
