### ISSUE TITLE
Mobile app installation page does not have structure

### ISSUE THREAD

**Issue by kochhar** [project-sunbird/project-sunbird.github.io#137]
http://www.sunbird.org/developer-docs/installation/install_mobile_setup/
Page requires structure.

cc: @Sunitashelar

**Comment by nawabahmadreshi** [comment]
@AmiableAnil ,mobile app installation seems to be incomplete ,can you please look into this. 
you can view the page here ,and for any additions click on edit at the top of the page.
http://www.sunbird.org/developer-docs/installation/install_mobile_setup/

**Comment by nawabahmadreshi** [comment]
@AmiableAnil  any update on this ?

**Comment by nawabahmadreshi** [comment]
Needs certain inputs from @AmiableAnil regarding repository address.
Under Review.
@Sunitashelar

**Comment by AmiableAnil** [comment]
https://github.com/project-sunbird/sunbird-android

@nawabahmadreshi

**Comment by nawabahmadreshi** [comment]
@AmiableAnil
 PR reviewed and merged.

**Comment by nawabahmadreshi** [comment]
reviewed and published

**Comment by kochhar** [comment]
@nawabahmadreshi @Sunitashelar instruction steps and code formatting is not consistent with the rest of the documentation pages.

**Comment by nawabahmadreshi** [comment]
fixed an re-published
