### ISSUE TITLE
Setting the Admin password in Key cloak

### ISSUE THREAD

**Issue by nawabahmadreshi** [project-sunbird/project-sunbird.github.io#141]
@coolbung  
As I got to know that don't use docker to set the admin password , can you please re verify the set of commands and update the same.
You can find the page here 
http://www.sunbird.org/developer-docs/installation/keycloak_realm_configuration/#link1-1-2
cc:
@kochhar 
@Sunitashelar

**Comment by coolbung** [comment]
Done. Check here 
http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/review/developer-docs/installation/keycloak_realm_configuration/#link1-1-2

Have removed references to docker. Do you see that in any other places it should not be ?

**Comment by nawabahmadreshi** [comment]
@coolbung 
Applied these changes, merged PR
