### ISSUE TITLE
Getting Started for developers 

### ISSUE THREAD

**Issue by nawabahmadreshi** [project-sunbird/project-sunbird.github.io#142]
A pdf and content on web needs to be made available to get developers an easy walkthrough the Sunbird.

**Comment by nawabahmadreshi** [comment]
Toc already done, it's work in progress.

**Comment by Basreena** [comment]
md is done:
https://github.com/project-sunbird/project-sunbird.github.io/blob/dev/pages/developer-docs/getting_started.md

The following sections are not done:
Content Editor Plugins (meeting with Juthika on Monday(8th Jan) to understand the same
Sunbird Platform Services
API Manager
Proxy

**Comment by Sunitashelar** [comment]
Done
