### ISSUE TITLE
Documentation on SSO and onboarding

### ISSUE THREAD

**Issue by Basreena** [project-sunbird/project-sunbird.github.io#144]
Create documentation on single sign on and onboarding and make it live on the website.

**Comment by Basreena** [comment]
.md page has been created: https://github.com/project-sunbird/project-sunbird.github.io/blob/dev/pages/developer-docs/onboarding_SSO

**Comment by nawabahmadreshi** [comment]
http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/review/developer-docs/overview_sso/

**Comment by nawabahmadreshi** [comment]
http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/review/developer-docs/overview_sso/

under review

**Comment by Sunitashelar** [comment]
Reviewed and published on site
