### ISSUE TITLE
Announcement feature updates on Sunbird Website 

### ISSUE THREAD

**Issue by nawabahmadreshi** [project-sunbird/project-sunbird.github.io#162]

**Comment by nawabahmadreshi** [comment]
@deepshikha2k5 
whats the current update?

**Comment by deepshikha2k5** [comment]
It is in progress.

**Comment by deepshikha2k5** [comment]
Hi @Sunitashelar please review the "announcements feature" document. Refer the QA link: 
http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/review/features-documentation/announcement/
