### ISSUE TITLE
#Bodhi Uploading HTML zip file

### ISSUE THREAD

**Issue by Kavya1403** [project-sunbird/project-sunbird.github.io#164]
How to upload existing html zip file content

**Comment by nawabahmadreshi** [comment]
@Kavya1403 
Follow the procedure below :
Log in> Workspace> Upload Content
Select the html folder> CLick upload

max upload size is 25mb

**Comment by Kavya1403** [comment]
What should be the folder structure for uploading the HTML zip. Whatever i am uploading it is saying unable to upload

**Comment by nawabahmadreshi** [comment]
@harishgilimi 
Can you please verify the folder structure required to upload HTML .zip file in the following image: 
![html1](https://user-images.githubusercontent.com/29115755/34596010-71579172-f202-11e7-8b73-6f4ff07d9e85.png)

cc:
@Sunitashelar

**Comment by harishgilimi** [comment]
@nawabahmadreshi  The index.html should be in lower case and zip name should be without special characters and spaces.

**Comment by Kavya1403** [comment]
I have followed the folder structure and index.html is in lowercase and the zip file name is without any special characters and spaces. Still it says unable to upload the content.

**Comment by nawabahmadreshi** [comment]
@Kavya1403 
Thanks for being patient, can you please upload that .zip file to your Google drive/any cloud storage and share the downloadable link here as comment. 
@harishgilimi can you please check this?

**Comment by kochhar** [comment]
This repository is primarily for documentation bugs. Please do not use this repository for user-facing support issues.
