### ISSUE TITLE
Org Moderator

### ISSUE THREAD

**Issue by Basreena** [project-sunbird/project-sunbird.github.io#167]
Document on:
Rights and permissions of Org Moderator

**Comment by Basreena** [comment]
RIghts and permissions updated in the document

https://docs.google.com/document/d/1Uy-M2Piq1mM9jZcW2MR-qpZv20pU-_UUpttICwW_9LI/edit#

**Comment by Basreena** [comment]
https://docs.google.com/document/d/1Uy-M2Piq1mM9jZcW2MR-qpZv20pU-_UUpttICwW_9LI/edit#
 User role matrix updated

**Comment by Sunitashelar** [comment]
document complete
