### ISSUE TITLE
New pages for Sunbird Back-end and actor services

### ISSUE THREAD

**Issue by nawabahmadreshi** [project-sunbird/project-sunbird.github.io#175]
@manzarul 
Sunbird Backend 
https://github.com/project-sunbird/project-sunbird.github.io/edit/dev/pages/developer-docs/installation/sunbird_backend.md

Actors Services
https://github.com/project-sunbird/project-sunbird.github.io/edit/dev/pages/developer-docs/installation/sunbird_actor_servc.md

**Comment by Sunitashelar** [comment]
@nawabahmadreshi - end date please...

**Comment by nawabahmadreshi** [comment]
@manzarul ,You have not updated the files, Kindly notify ETA required to complete this from your end.

**Comment by manzarul** [comment]
@nawabahmadreshi ,
 I updated the file same day and created a pull request.
you can find my pull request here:
1. https://github.com/project-sunbird/project-sunbird.github.io/pull/178/commits/e68b29140178d724fe8a68e220b0cc13cedae251
2. https://github.com/project-sunbird/project-sunbird.github.io/pull/177/commits/a4c9ae3cbd830be642ac1140c4e389eea5fe15fd

i updated with same link which i got from you.
