### ISSUE TITLE
Procedure document for creating books on DIKSHA

### ISSUE THREAD

**Issue by Basreena** [project-sunbird/project-sunbird.github.io#187]
Create a  procedure document in ppt format for creating books on DIKSHA

**Comment by Basreena** [comment]
Document created, review pending

**Comment by Sunitashelar** [comment]
changed milestone

**Comment by Basreena** [comment]
Completed
https://docs.google.com/presentation/d/11xWz2_wpSgRs6fNlOCTrQZvChX_Ij8IJK5EUJGOZL3w/edit
