### ISSUE TITLE
API documentation (Announcements)

### ISSUE THREAD

**Issue by nawabahmadreshi** [project-sunbird/project-sunbird.github.io#189]
9/1/2017

**Comment by nawabahmadreshi** [comment]
Submitted for review

**Comment by nawabahmadreshi** [comment]
Expecting sign off by EoD 12/1/2017 or  Early morning on Tuesday .#Slack

**Comment by gsbajaj72** [comment]
@nawabahmadreshi As discussed, please update the document

**Comment by nawabahmadreshi** [comment]
Already changed the doc, uploaded to QA, I will send you the link

**Comment by deepshikha2k5** [comment]
link to the published content: http://www.sunbird.org/apis/announcements/
