### ISSUE TITLE
Review PRs and content fixed and staged on Prod. 

### ISSUE THREAD

**Issue by nawabahmadreshi** [project-sunbird/project-sunbird.github.io#199]
@rjshrjndrn The content is live , check and sidebar will get updated in 10-15 mins.

**Comment by nawabahmadreshi** [comment]
Done

**Comment by nawabahmadreshi** [comment]
http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/review/developer-docs/installation/deploy_sb_services/

@rjshrjndrn  check the content and sidebar , all changes done and updated.

**Comment by nawabahmadreshi** [comment]
Done

**Comment by rjshrjndrn** [comment]
Thank you, @nawabahmadreshi , as always, you're awesome. :+1:
