### ISSUE TITLE
Create Lesson Plan documentation for Sunbird

### ISSUE THREAD

**Issue by Sunitashelar** [project-sunbird/project-sunbird.github.io#206]
**Project Name:** Sunbird

**Release Version Number:**

**Issue Category:** New documentation

**Priority:** 1

**Issue Description:** Create Lesson Plan documentation for Sunbird

**Sequence of Steps Undertaken:** NA

**Expected Behaviour:** NA

**Actual Behaviour:** NA

**Environment In which Issue Encountered:** NA

**Supporting Files:** NA

**Comment by deepshikha2k5** [comment]
Hi @Sunitashelar ,

I have created the Lesson Plan document. Refer the link for peer review:
http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/review/features-documentation/lessonplan/
While reviewing the document you can change the pipeline to "Review/QA"

cc: @Basreena 
     @nawabahmadreshi

**Comment by deepshikha2k5** [comment]
Content created on Lesson plan and published live on Sunbird website. Refer link: http://www.sunbird.org/features-documentation/lessonplan/
