### ISSUE TITLE
Review Announcements Feature doc with Bajaj

### ISSUE THREAD

**Issue by Sunitashelar** [project-sunbird/project-sunbird.github.io#207]
**Project Name:** Sunbird

**Release Version Number:**

**Issue Catergory:** Docs review

**Priority:**1

**Issue Description:** Review for completeness and accuracy 

**Sequence of Steps Undertaken:** NA

**Expected Behaviour:** NA

**Actual Behaviour:** NA

**Environment In which Issue Encountered:** NA

**Supporting Files:** NA

**Comment by nawabahmadreshi** [comment]
Hi @gsbajaj72  ,

We would like to inform you that, all the request for any new documents:
- You need to follow contribution guidelines http://www.sunbird.org/contributions/contribution_guidelines
- You can create an issue in https://github.com/project-sunbird/project-sunbird.github.io/issues/new
- Create an issue title "request for a new markdown page" and submit the issue.
Additionally, you can convert your google doc to .md file by the adding the following sheet addon "Export as Markdown" 
 CC: @Sunitashelar @kochhar

**Comment by gsbajaj72** [comment]
https://github.com/project-sunbird/project-sunbird.github.io/issues/217

**Comment by nawabahmadreshi** [comment]
reviewed by Bajaj (23/01/2018) and published
