### ISSUE TITLE
Create 6 new categories of API docs in Swagger 

### ISSUE THREAD

**Issue by Sunitashelar** [project-sunbird/project-sunbird.github.io#209]
**Project Name:** Sunbird

**Release Version Number:**

**Issue Catergory:** API documentation

**Priority:** 1

**Issue Description:** Document 6 new categories of APIs viz. Badges, Audience, Audit, Geo Location, Masterkey, Objectstore.

**Sequence of Steps Undertaken:** 

**Expected Behaviour:**

**Actual Behaviour:**

**Environment In which Issue Encountered:**

**Supporting Files:**

**Comment by nawabahmadreshi** [comment]
Done 21/01/2017
