### ISSUE TITLE
Developer Install docs code blocks are broken

### ISSUE THREAD

**Issue by kochhar** [project-sunbird/project-sunbird.github.io#21]
@kochhar commented on [Fri Oct 27 2017](https://github.com/project-sunbird/sunbird-commons/issues/95)

@nawabahmadreshi Please see this page: http://www.sunbird.org/developer-docs/developer_install/

Bottom part of the page:
Edit the application config:

The code block formatting is broken. The code should be formatted as a block and not as inline code. When formatting it as a block one config entry should appear on every line.
http://www.sunbird.org/developer-docs/developer_install/

---

@nawabahmadreshi commented on [Fri Oct 27 2017](https://github.com/project-sunbird/sunbird-commons/issues/95#issuecomment-339902291)

@kochhar, agreed and will do the necessary changes. 

---

@kochhar commented on [Thu Nov 02 2017](https://github.com/project-sunbird/sunbird-commons/issues/95#issuecomment-341349781)

@nawabahmadreshi could you estimate when will this be completed? Formatting is still broken on the website for multiple sections.

cc: @Sunitashelar

**Comment by lakhanmandloi** [comment]
Fixed. @kochhar @nawabahmadreshi
