### ISSUE TITLE
Create Admin dashboard documentation for Sunbird 

### ISSUE THREAD

**Issue by Sunitashelar** [project-sunbird/project-sunbird.github.io#211]
**Project Name:** Sunbird

**Release Version Number:**

**Issue Category:** New documentation

**Priority:** 1

**Issue Description:** Create documentation for Admin Dashboard in Sunbird

**Sequence of Steps Undertaken:** NA

**Expected Behaviour:**NA

**Actual Behaviour:**NA

**Environment In which Issue Encountered:**NA

**Supporting Files:**NA

**Comment by deepshikha2k5** [comment]
@Sunitashelar 

Please review the admin dashboard documentation. Refer the below link:
https://github.com/project-sunbird/project-sunbird.github.io/blob/dev/pages/features-documentation/admindashboard.md

cc: 
@Basreena 
@nawabahmadreshi

**Comment by deepshikha2k5** [comment]
Content is published live on Sunbird website
