### ISSUE TITLE
Create page for announcement onboarding

### ISSUE THREAD

**Issue by gsbajaj72** [project-sunbird/project-sunbird.github.io#217]
I need a page to document announcement onboarding process after deployment.

**Comment by nawabahmadreshi** [comment]
@gsbajaj72 
Hello,
You can post your content here in this file:
https://github.com/project-sunbird/project-sunbird.github.io/blob/dev/pages/developer-docs/announcement_onboarding.md

**Comment by nawabahmadreshi** [comment]
done & published
