### ISSUE TITLE
Developer documentation should have links back to source

### ISSUE THREAD

**Issue by kochhar** [project-sunbird/project-sunbird.github.io#22]
@kochhar commented on [Fri Nov 03 2017](https://github.com/project-sunbird/sunbird-commons/issues/96)

Developer documentation is incomplete and sometimes gets out of date. When external users find errors in the docs, they must be able to edit and fix the errors. Each doc must have a link back to its source file, plus links to documentation for how to submit docs corrections.

Document creation will become more collaborative.

cc: @Sunitashelar, @nawabahmadreshi 

---

@kochhar commented on [Fri Nov 03 2017](https://github.com/project-sunbird/sunbird-commons/issues/96#issuecomment-341615864)

cc: @lakhanmandloi

**Comment by lakhanmandloi** [comment]
@kochhar @Sunitashelar @nawabahmadreshi  - Hi , "Edit this page link" added . 
Please check on site - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/

**Comment by kochhar** [comment]
Hi Lakhan, could this be placed in the footer of the page also, with the
text:

'Found an error? Fix this page'

**Comment by kochhar** [comment]
Lakhan, it's looking a bit intrusive on the page at the top. I think we
need to adjust size and positioning.

**Comment by lakhanmandloi** [comment]
@kochhar Is this better ? - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/developer-docs/installation/installing_sunbirdon_laptop/

Also added 'Found an error? Fix this page' at the bottom of the page.

**Comment by kochhar** [comment]
This is better! But it's still somewhat disconnected from the rest of the
page. See the enclosed attachment for an alternate placement.

[image: Screen Shot 2017-11-08 at 1.02.41 PM.png]

**Comment by lakhanmandloi** [comment]
@kochhar Hi, can you please attach image again? i cant see it.

**Comment by kochhar** [comment]
<img width="658" alt="screen shot 2017-11-08 at 1 02 41 pm" src="https://user-images.githubusercontent.com/103850/32550092-dcf85d68-c4b1-11e7-809e-2a8bdfc2c93d.png">

**Comment by lakhanmandloi** [comment]
@kochhar Done

**Comment by kochhar** [comment]
The edit link goes to the source file, but it's not in the edit view.

This should be the edit url (note the path):
https://github.com/project-sunbird/project-sunbird.github.io/*edit/*
dev/pages/developer-docs/installation/installing_sunbirdon_laptop.md
for this documentation page:
http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/developer-docs/installation/installing_sunbirdon_laptop/

**Comment by lakhanmandloi** [comment]
Hi @kochhar,

Links updated to open in edit view. 
Please check on http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/developer-docs/installation/installing_sunbirdon_laptop/

**Comment by kochhar** [comment]
Works as expected. Great!

**Comment by lakhanmandloi** [comment]
Thank you! Closing this issue.

**Comment by kochhar** [comment]
@lakhanmandloi when will this be live?

**Comment by lakhanmandloi** [comment]
@kochhar This is gone to prod.
