### ISSUE TITLE
Installation guides should list OS prerequisites for installation

### ISSUE THREAD

**Issue by kochhar** [project-sunbird/project-sunbird.github.io#23]
@kochhar commented on [Fri Nov 03 2017](https://github.com/project-sunbird/sunbird-commons/issues/97)

The laptop installation guide is missing the information that install needs to be done on a linux OS. 
Windows installation instructions should be provided as a separate section.

The same should be applied for the medium sized installation guide. Some parts of the application may not run on windows. The appropriate sections must be updated to indicate this.

**Comment by nawabahmadreshi** [comment]
@kochhar 
To install Sunbird, your laptop should have the following minimum system requirements:

   - Linux operating system 
   - RAM: 1GB
   - CPU: 2 cores, >2 GHz
   - root access (should be able to sudo)

Is this right?

**Comment by kochhar** [comment]
os xAre you sure about this? What about Mac?

**Comment by nawabahmadreshi** [comment]
@kochhar , As far as I know its possible for developers to install it on Macintosh OS as its Linux based. 
So what should be in OS column then.
Kindly suggest so that we close it .

**Comment by kochhar** [comment]
Requirements should include OS X. Please get it answered from the
developers.

**Comment by nawabahmadreshi** [comment]
@kochhar ,  can you point me to the right person.

**Comment by kochhar** [comment]
Same person who provided the installation guide.

**Comment by nawabahmadreshi** [comment]
http://www.sunbird.org/developer-docs/installation/installing_sunbirdon_laptop/
