### ISSUE TITLE
Table Rendering issues on docs website  (probably .css issue)

### ISSUE THREAD

**Issue by nawabahmadreshi** [project-sunbird/project-sunbird.github.io#234]
Top Row is always rendered incorrectly, it does not follow dimensions set for the table. 
@lakhanmandloi @himangi , Can you check this and do the needful. 
For your reference, kindly check:
http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/review/glossary
you can click on any letter and view tables.

**Comment by lakhanmandloi** [comment]
@nawabahmadreshi Hi, Fixed.

**Comment by nawabahmadreshi** [comment]
Hi, @lakhanmandloi  kindly check the issue again (the header row sizes), also the table header rows formatting ( branded row theme) 
i.e the header row looks similar to other rows.

**Comment by lakhanmandloi** [comment]
Hello @nawabahmadreshi , 

Not getting your point. Can you pls elaborate ?

![screenshot-127 0 0 1-4000-2018-01-31-17-20-53-699](https://user-images.githubusercontent.com/30073416/35621654-2943094e-06ab-11e8-9f71-139dc5edef48.png)
