### ISSUE TITLE
Add new page "Actor System"

### ISSUE THREAD

**Issue by nawabahmadreshi** [project-sunbird/project-sunbird.github.io#237]
@manzarul 
Kindly review 
http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/review/developer-docs/installation/sunbird_actor_servc/
https://github.com/project-sunbird/project-sunbird.github.io/pull/178

**Comment by deepshikha2k5** [comment]
The content is published live on Sunbird website. Refer link: http://www.sunbird.org/developer-docs/installation/sunbird_actor_servc/
