### ISSUE TITLE
Contribution Section for Sunbird Website

### ISSUE THREAD

**Issue by kochhar** [project-sunbird/project-sunbird.github.io#25]
@nawabahmadreshi commented on [Mon Oct 09 2017](https://github.com/project-sunbird/sunbird-commons/issues/72)

Hello Team, 
We need to put up the contribution section for sunbird website . 
Put comments and suggestions if any. 
cc:
@Sunitashelar 
@kochhar 
@deepshikha2k5 
@Basreena 
@vrayulu 

---

@nawabahmadreshi commented on [Mon Oct 09 2017](https://github.com/project-sunbird/sunbird-commons/issues/72#issuecomment-335100219)

@kochhar , kindly suggest the point of contact for contribution section .
Also once you had said that we have some wiki or some doc related to it , can you provide the link .

**Comment by deepshikha2k5** [comment]
The contribution section on the Sunbird website was created. Though we have kept the issue open, since we need to update the existing documentation with the process that has recently changed wef. 28/12/2017

**Comment by kochhar** [comment]
Could you please share the link to the section?

**Comment by nawabahmadreshi** [comment]
@kochhar, Contribution section will be listed as a separate section as you sign off this doc
http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/review/contributions/filing_a_bug/

Also further suggested sections will be added appropriately

**Comment by deepshikha2k5** [comment]
Hi @kochhar 

Kindly review the document, to incorporate the review changes. Refer the link for the review:
http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/review/contributions/filing_a_bug/

**Comment by kochhar** [comment]
@deepshikha, the preamble/pre-requisites part of the document is too long.
Second, the document is focused a lot on the steps on how to use github. It
would be more desire-able to strip this from the document and focus on how
to write a good bug report. The rest people are already doing and don't
need docs.

**Comment by deepshikha2k5** [comment]
The document is published on Sunbird Website. Hence, closing the issue. Published link: http://www.sunbird.org/contributions/filing_a_bug/
