### ISSUE TITLE
Each "href" to external link needs to be opened in new tab

### ISSUE THREAD

**Issue by kochhar** [project-sunbird/project-sunbird.github.io#26]
@nawabahmadreshi commented on [Fri Oct 13 2017](https://github.com/project-sunbird/sunbird-commons/issues/84)

We need to enable opening of external links in a new tab for richer user experience .
@lakhanmandloi 
cc:
@Sunitashelar 

---

@nawabahmadreshi commented on [Mon Oct 16 2017](https://github.com/project-sunbird/sunbird-commons/issues/84#issuecomment-336789449)

@kochhar 
Opening external links in the same tab,  creates back-button fatigue for users. Every time the user goes to an external website they have to hit the back button to go back to your website. If they decide to click the links on the other website, they have to hit the back button even more times to get back to the site. 
Also opening the external links in new tabs allows users to scan the page once, click on all the relevant links and start consuming  information. The user doesn’t have to keep going back to the source page to continue scanning for more links to click. There’s less interruption in their user flow, thus richer user experience.
Opening external links in the same tab doesn’t just overwork the user, it also overworks the website. Every time the user goes back to the website it uses site resources to load the page.
cc:
@Sunitashelar 

---

@lakhanmandloi commented on [Thu Oct 26 2017](https://github.com/project-sunbird/sunbird-commons/issues/84#issuecomment-339600939)

@nawabahmadreshi  yes , i agree. External links should be opened in new tabs. Can you pls mention where we need such ? we will correct them .

**Comment by kochhar** [comment]
@lakhanmandloi @nawabahmadreshi is this fixed?

**Comment by lakhanmandloi** [comment]
@nawabahmadreshi @kochhar This is fixed now.
