### ISSUE TITLE
Not able to download API swagger files from "Sunbird Website" 

### ISSUE THREAD

**Issue by nawabahmadreshi** [project-sunbird/project-sunbird.github.io#264]
When we try to download any API swagger doc file from sunbird website. The download is failing 

![dwnld failed](https://user-images.githubusercontent.com/29115755/36363408-d7721aa8-1562-11e8-9857-abd2aca719da.png)

**Comment by nawabahmadreshi** [comment]
@himangi  can we close this please 

CC:
@lakhanmandloi

**Comment by lakhanmandloi** [comment]
Hello @nawabahmadreshi ,

Issue has been fixed and committed in repo.
It will automatically go in the next deployment. 

Thanks!

**Comment by nawabahmadreshi** [comment]
@lakhanmandloi thanks, Will check once @Sunitashelar will give it a prod build

**Comment by nawabahmadreshi** [comment]
verified and closing the issue
