### ISSUE TITLE
Upgrade of NGINX

### ISSUE THREAD

**Issue by Abhishek-Govula** [project-sunbird/project-sunbird.github.io#265]
Hi,
  Can you please provide the latest version of NGINX for the proxy service. The current proxy service is using NGINX version# 1.13.3 which is obsolete.

**Comment by steotia** [comment]
@mathewjpallan can you please get your team to triage it? Or else if it is a configuration which @Abhishek-Govula can handle, let him know how to do it.
cc @Manojvv

**Comment by steotia** [comment]
How are you deploying the stack?
Let me know the deployment steps (basic).

**Comment by Abhishek-Govula** [comment]
@steotia  - I am running the deployment script. Inside sunbird-devops/deploy/deploy-proxy.sh directory

**Comment by kochhar** [comment]
Issue moved to [project-sunbird/sunbird-devops #57](https://github.com/project-sunbird/sunbird-devops/issues/57) via [**ZenHub**](https://www.zenhub.com/)

**Comment by kochhar** [comment]
Folks, moving this issue to devops, this repository is for Sunbird documentation.
