### ISSUE TITLE
Framework category create API show incorrect URL in swagger documentation

### ISSUE THREAD

**Issue by kochhar** [project-sunbird/project-sunbird.github.io#269]
Category create API doc is showing the API url as /framework/v1/framework/v1/category/create, the correct URL should be /framework/v1/category/create

**Comment by nawabahmadreshi** [comment]
Done

https://staging.open-sunbird.org/framework/v1/create
![swagger](https://user-images.githubusercontent.com/29115755/36579500-6d565556-1889-11e8-9b7b-153ee2fc5971.png)
