### ISSUE TITLE
Fix outdated Sunbird v1.0 installation documentation

### ISSUE THREAD

**Issue by kochhar** [project-sunbird/project-sunbird.github.io#28]
Epic to track the fixes required in Sunbird 1.0 installation documentation which has drifted out of date with the codebase.

**Comment by nawabahmadreshi** [comment]
@kochhar 
done 
Kindly check this
http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/developer-docs/installation/medium_scale_deploy/
(updated this)
APIs also updated , I will go for prod if all is ok.

**Comment by nawabahmadreshi** [comment]
@kochhar , Kindly cross check is the current version the latest one for installation. 
cc:
@Sunitashelar

**Comment by kochhar** [comment]
Seems right to me. @harishgillimi please confirm the portal installation
instructions:
http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/developer-docs/installation/installing_sunbirdon_laptop/
