### ISSUE TITLE
docs deployment should build staging versions for pull requests

### ISSUE THREAD

**Issue by kochhar** [project-sunbird/project-sunbird.github.io#30]
when new pull requests are sent to the docs site, the CI should automatically build a new site version and make it available for inspection

**Comment by lakhanmandloi** [comment]
Hi @kochhar ,

This feature is ready for review. For each PR opened a new site will be created for the users to review. Along with this the hold build promotion is also done.(Fix for - https://github.com/project-sunbird/project-sunbird.github.io/issues/14) .

Can you please schedule when we can review all these process ?

Also i will need a bucket for the review site.

**Comment by lakhanmandloi** [comment]
Hi @kochhar ,

This feature is ready to review and deploy. We will not need any more bucket. Here is how i am using single bucket to hold all things -

1. For each PR opened, the url will be - staging.sunbird.org/pr/PR-NO
2. For each Build Version, the url will be - staging.sunbird.org/v/TAG-NO

So we are using single bucket to hold all - review, staging etc

Let me know when you can review this process.

Thanks!

**Comment by lakhanmandloi** [comment]
Hi @kochhar ,

Can you pls review this doc - https://docs.google.com/document/d/1yAxIjWs3AQU-zE4wKTxOsGcW0G34mRsYrPs_vLcTaAo/edit#
Please let me know you feedback on same.

Thanks!

cc @coolbung @parthlawate

**Comment by coolbung** [comment]
Looks ok in general. However, do we really need each commit creating a site under `/review/` ?

**Comment by lakhanmandloi** [comment]
@coolbung 

Hi,

For commit - `/review/` site will get updated rather then created a new site inside it. 
For PR & tags - new sites will be created in their respective folders.

**Comment by coolbung** [comment]
That would be confusing since there is no control on who can commit when. Also, the only real way to get commits into the repo would be via a merge request. So I feel we could do without the review folder

**Comment by lakhanmandloi** [comment]
So that means Docs team should follow the same process - send pr for changes. 
@kochhar  - ??

**Comment by kochhar** [comment]
Not yet, docs teams is still working without a PR flow. Probably will stay
this way for another few months till the docs process and requirements
stabilise.
