### ISSUE TITLE
documentation for docs building

### ISSUE THREAD

**Issue by kochhar** [project-sunbird/project-sunbird.github.io#31]
@lakhanmandloi could you please add a README file to this repo which explains how to create a new docs dev build and a new docs prod build

**Comment by lakhanmandloi** [comment]
Duplicate Issue - https://github.com/project-sunbird/project-sunbird.github.io/issues/15

**Comment by lakhanmandloi** [comment]
@kochhar Hi, I will be working the documentation part today, This is a duplicate issue of https://github.com/project-sunbird/project-sunbird.github.io/issues/15 so closing this issue.
