### ISSUE TITLE
Table of Content for each Documentation page

### ISSUE THREAD

**Issue by lakhanmandloi** [project-sunbird/project-sunbird.github.io#33]

**Comment by lakhanmandloi** [comment]
@kochhar - Can you please check dynamic TOC - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/developer-docs/installation/installing_sunbirdon_laptop/

This is based on https://github.com/dafi/jekyll-toc-generator

**Comment by kochhar** [comment]
Nice work @lakhanmandloi. Could the width be adjusted to be similar to how
wikipedia manages their ToC widths?

**Comment by lakhanmandloi** [comment]
@kochhar Thank you!
Can you pls check now at - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/developer-docs/installation/installing_sunbirdon_laptop/
Width will automatically adjust as per the content length in this case.
Is this okay?

**Comment by kochhar** [comment]
Seems good. For alignment, the links above the ToC should be aligned with
the content inside the ToC. Also the font size for the Edit and Report
error links could be reduced by 2px.

**Comment by lakhanmandloi** [comment]
Hi @kochhar  - Updated

**Comment by kochhar** [comment]
Looks good to me.

**Comment by kochhar** [comment]
@lakhanmandloi when will this be live?

**Comment by lakhanmandloi** [comment]
@kochhar this is on prod now
