### ISSUE TITLE
Add search functionality

### ISSUE THREAD

**Issue by lakhanmandloi** [project-sunbird/project-sunbird.github.io#35]

**Comment by lakhanmandloi** [comment]
Hi @kochhar, As per our discussion , Google custom search integrated. Can you pls review it -
There are 2 variations
1. For landing page - on the top header
2. For Documentation pages - on sidebar

URL - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/
http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/architecture/

cc : @Sunitashelar @nawabahmadreshi @Basreena

**Comment by kochhar** [comment]
@lakhanmandloi the popover is nice but there are concerns. please see the attached image: ads are showing up on the sunbird.org site. in the developer docs version, the first screenful has only ads. we can't serve google ads on the sunbird site. also the popover is covering the search box which hides the search query made. suggest we open the google search url in a new tab so we don't alter the experience on the sunbird site itself

![screen shot 2017-11-10 at 1 40 23 pm](https://user-images.githubusercontent.com/103850/32648649-d8818720-c61c-11e7-9d71-9ba955bdd0b3.png)

![screen shot 2017-11-10 at 1 43 10 pm](https://user-images.githubusercontent.com/103850/32648708-2134f358-c61d-11e7-85da-f8223dcb33be.png)

**Comment by lakhanmandloi** [comment]
Hi @kochhar ,
Updated, Can you pls check it now ?

**Comment by lakhanmandloi** [comment]
Hi @kochhar ,

**Comment by kochhar** [comment]
Looks good Lakhan.
