### ISSUE TITLE
Sunbird installation instructions should have new installers request a QA API key initially

### ISSUE THREAD

**Issue by kochhar** [project-sunbird/project-sunbird.github.io#55]
@kochhar commented on [Thu Nov 09 2017](https://github.com/project-sunbird/sunbird-commons/issues/106)

[Installation instructions](http://www.sunbird.org/developer-docs/installation/medium_scale_deploy/) instruct users to generate an API token from production EkStep. The instructions should instruct users to generate API tokes from EkStep QA: https://github.com/project-sunbird/sunbird-commons/wiki/Obtaining-API-token-for-accessing-ekstep-APIs

---

@kochhar commented on [Thu Nov 09 2017](https://github.com/project-sunbird/sunbird-commons/issues/106#issuecomment-343069853)

@coolbung also as part of this change please move the instructions for generating an API key to the Sunbird documentation site. Ideally, we should reference the EkStep instructions so that we do not fall behind or get out of sync.

**Comment by nawabahmadreshi** [comment]
@endeepak @coolbung  any update on this ?

**Comment by coolbung** [comment]
I've updated the docs. Please check the preview link and verify

**Comment by nawabahmadreshi** [comment]
done , currently on QA for review

**Comment by nawabahmadreshi** [comment]
@kochhar 
Kindly check and verify the changed content.

http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/review/developer-docs/installation/medium_scale_deploy/

**Comment by kochhar** [comment]
- Links on the page are opening in a new window. This should not be the
case.
- Some places there are missing spaces after full-stop.

**Comment by kochhar** [comment]
@Sunitashelar are the fixes done?

**Comment by Sunitashelar** [comment]
@kochhar the information has been added in the installation page. Working on the change in the tree structure and telemetry pages.



Sent from Mail for Windows 10
