### ISSUE TITLE
Missing mobile app documentation

### ISSUE THREAD

**Issue by AmiableAnil** [project-sunbird/project-sunbird.github.io#64]
Documentation is missing for sunbird mobile app build.

**Comment by nawabahmadreshi** [comment]
Step 6: Generate key and secrets for mobile app
https://github.com/project-sunbird/project-sunbird.github.io/blob/dev/pages/developer-docs/installation/medium_scale_deploy.md

we only have this information

**Comment by nawabahmadreshi** [comment]
I am already following this 
https://github.com/project-sunbird/sunbird-commons/issues/63
cc:
@Sunitashelar

**Comment by AmiableAnil** [comment]
Steps to build APK from git repo:

1. Install Android Studio and configure it.
2. Clone GitHub sunbird-mobile repo into it.
3. Get the MOBILE_APP_KEY and MOBILE_APP_SECRET from EkStep.
4. If You want to change the logo name go to sunbird-mobile/dui-demo/src/main/res/values/strings.xml and give the required app name.
5. For app logo changing goto sunbird-mobile/dui-demo/src/main/res folder, here in all mipmap folders and drawable folder replace ic_launcher.png image with your logo. Logo name should be ic_launcher.png
6. Change Application Id to your application id in provider-authorities.xml file located at sunbird-mobile/dui-demo/src/main/res/values path.
Example- .fileprovider
.profiles
.telemetry -> change all the data similarly.

**Comment by nawabahmadreshi** [comment]
@AmiableAnil , 
I am providing you a link to a markdown file
https://github.com/project-sunbird/project-sunbird.github.io/blob/dev/pages/developer-docs/installation/creating_your_genie_app.md
Here you can put down all the necessary information .

**Comment by nawabahmadreshi** [comment]
@AmiableAnil  any updates on this .

**Comment by nawabahmadreshi** [comment]
@AmiableAnil ,mobile app installation seems to be incomplete ,can you please look into this.
You can view the page here ,and for any additions click on edit at the top of the page.
http://www.sunbird.org/developer-docs/installation/install_mobile_setup/

**Comment by nawabahmadreshi** [comment]
@AmiableAnil  any update ?

**Comment by nawabahmadreshi** [comment]
https://github.com/project-sunbird/project-sunbird.github.io/pull/153

**Comment by nawabahmadreshi** [comment]
Done
