### ISSUE TITLE
Keycloak realm config 

### ISSUE THREAD

**Issue by coolbung** [project-sunbird/project-sunbird.github.io#65]
The realm configuration page is missing is the sunbird installation docs. Can you please add

Here's the link to the wiki - https://github.com/project-sunbird/sunbird-commons/wiki/Keycloak-realm-configuration

**Comment by nawabahmadreshi** [comment]
@coolbung sure will do that , but I need to understand where to put the content in medium scale deployment . 

http://www.sunbird.org/developer-docs/installation/medium_scale_deploy/

**Comment by coolbung** [comment]
The realm import and config steps are same for both installation modes. So you can create the page and link the same from both places.

**Comment by nawabahmadreshi** [comment]
@coolbung check the following link to verify the contents.
http://www.sunbird.org/developer-docs/installation/keycloak_realm_configuration/

**Comment by coolbung** [comment]
This page will undergo improvement since Amol is currently installing Keycloak based on documentation and he’ll send PRs for improvement.

On Fri, Jan 5, 2018 at 10:56 AM, Nawab <notifications@github.com> wrote:
@coolbung [https://github.com/coolbung] check the following link to verify the contents.
http://www.sunbird.org/developer-docs/installation/keycloak_realm_configuration/ [http://www.sunbird.org/developer-docs/installation/keycloak_realm_configuration/]

**Comment by Sunitashelar** [comment]
Closed for now. Reopen when changes are required to be done by Amol.
