### ISSUE TITLE
 "Provisioning servers" (Manual process) steps are missing 

### ISSUE THREAD

**Issue by nawabahmadreshi** [project-sunbird/project-sunbird.github.io#66]
Referencing to this medium scale installation doc. , 
https://github.com/project-sunbird/sunbird-devops/blob/master/Installation.md#manual
The manual steps are probably missing .
Providing you the link to an empty .md file where you can put in all the necessary information.
The link to the file is here :
 https://github.com/project-sunbird/project-sunbird.github.io/edit/dev/pages/developer-docs/installation/provisioning-servers.md

cc:
@Sunitashelar

**Comment by lakhanmandloi** [comment]
@nawabahmadreshi @steotia 

Update file link is here - https://github.com/project-sunbird/project-sunbird.github.io/edit/dev/pages/developer-docs/installation/provisioning-servers.md

**Comment by nawabahmadreshi** [comment]
@steotia , any update on this ?

**Comment by steotia** [comment]
The manual section is updated at the same location https://github.com/project-sunbird/sunbird-devops/blob/master/Installation.md#manual

I don't need a separate markdown. I do not recommend manual steps from our side since they are very exhaustive, error prone, have better documentation on the web. I would rather ask people to perfect automation and if they wish, read up the code to understand it better.

However, I have added context in Manual so that people know what they are getting into if they want to setup everything manually.

And yes, please no installation on laptops for a platform installation! For laptops, we have a separate section.

**Comment by kochhar** [comment]
@nawabahmadreshi please delete the section on manual setup of servers from the sunbird.org docs.

@steotia the canonical source of truth for sunbird installation docs is project-sunbird/project-sunbird.github.io/ please direct edits to this repo if any are made.

**Comment by nawabahmadreshi** [comment]
already done

**Comment by kochhar** [comment]
@nawabahmadreshi section on manual setup is not removed from the website.
http://www.sunbird.org/developer-docs/installation/provisioning_servers/#manual-process

**Comment by nawabahmadreshi** [comment]
@kochhar, production build was planned for today that why you were not able to see the changes,. 
http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/review/developer-docs/installation/provisioning_servers/

**Comment by kochhar** [comment]
Manual process is still present.

**Comment by coolbung** [comment]
@kochhar I suggest we retain the manual section, since the automation is only done for Azure. It is certainly needed to understand what kind of VMs are needed if someone is installing on Google or Amazon for instance.

**Comment by kochhar** [comment]
@coolbung The manual section says using the manual process is not recommended. This needs to go. 

I've reformatted the document and removed the section. I've added in a section which needs to be filled in installing Docker swarm for manual provisioning.

**Comment by coolbung** [comment]
Ok. Although I don't see the docker related instructions in the manual section.

When I did the provisioning on my google cloud, docker seems to have gotten installed via the `install-deps.sh` line from [this page](https://github.com/project-sunbird/sunbird-devops/blob/4f1ec8c3457c237aba8fd75cb99e5efd14e43605/Installation.md#step-4-setup-application-and-core-services)

So adding the missing instructions to run `install-deps.sh` should be sufficient I think. 

Let me know if I should go ahead and add it or if you want to take a different approach.

**Comment by kochhar** [comment]
Sounds good! Please make the fixes.

**Comment by coolbung** [comment]
The deps installation is already mentioned in the "preparation" section here -
http://www.sunbird.org/developer-docs/installation/deploy_sb_services/

So this can be closed.
