### ISSUE TITLE
Update Installation Overview Links in sunbird-portal repo

### ISSUE THREAD

**Issue by lakhanmandloi** [project-sunbird/project-sunbird.github.io#82]
Hi @kochhar @vrayulu ,

Can you please update links in Sunbird-Portal Repo details (https://github.com/project-sunbird/sunbird-portal) from http://www.sunbird.org/developer-docs/installation_overview/ to http://www.sunbird.org/developer-docs/installation/ 

First one is old link and later one is updated link. 

@nawabahmadreshi can you please delete source of http://www.sunbird.org/developer-docs/installation_overview/ after verifying the latest content is already available in http://www.sunbird.org/developer-docs/installation/ 

Thanks!

**Comment by nawabahmadreshi** [comment]
@lakhanmandloi sure , i will cross check and move/delete the files accordingly .

**Comment by kochhar** [comment]
@nawabahmadreshi what is the status of this issue?

cc: @Sunitashelar
