### ISSUE TITLE
Installation documentation needs section on accessing Telemetry data

### ISSUE THREAD

**Issue by kochhar** [project-sunbird/project-sunbird.github.io#93]
See source issue filed: https://github.com/project-sunbird/sunbird-commons/issues/112

Questions asked:
1. What are the APIs used to access telemetry?
2. What are the telemetry datasets available?
3. What kind of permissions are required to access the dataset?

**Comment by kochhar** [comment]
@Sunitashelar when will this be taken up?

**Comment by deepshikha2k5** [comment]
Telemetry Document is created and live on sunbird.org. We will link the telemetry doc with installation document. 

Refer link for issue created and closed on telemetry doc (https://github.com/project-sunbird/project-sunbird.github.io/issues/163)
