### ISSUE TITLE
Need for a FAQ doc creation 

### ISSUE THREAD

**Issue by deepshikha2k5** [project-sunbird/project-sunbird.github.io#94]
@manzarul Please take care of the content for the Sunbird FAQ doc. Find the link below:
https://github.com/project-sunbird/project-sunbird.github.io/blob/dev/pages/developer-docs/sunbird_faq.md

Please update the same in the issue tracker sheet as well.

**Comment by Sunitashelar** [comment]
Added page for Troubleshooting in Developer Doc section. Resolved.
